# Generated by Django 4.0.4 on 2022-04-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamkorlar',
            new_name='Partner',
        ),
    ]
